export const values = [
  { Dia: "Dia 01", Valor: 10, Categoria: "Atual" },
  { Dia: "Dia 01", Valor: 8, Categoria: "Com Novo Produto" },
  { Dia: "Dia 02", Valor: 20, Categoria: "Atual" },
  { Dia: "Dia 02", Valor: 16, Categoria: "Com Novo Produto" },
  { Dia: "Dia 03", Valor: 30, Categoria: "Atual" },
  { Dia: "Dia 03", Valor: 24, Categoria: "Com Novo Produto" },
  { Dia: "Dia 04", Valor: 40, Categoria: "Atual" },
  { Dia: "Dia 04", Valor: 32, Categoria: "Com Novo Produto" },
  { Dia: "Dia 05", Valor: 50, Categoria: "Atual" },
  { Dia: "Dia 05", Valor: 40, Categoria: "Com Novo Produto" },
  { Dia: "Dia 06", Valor: 60, Categoria: "Atual" },
  { Dia: "Dia 06", Valor: 48, Categoria: "Com Novo Produto" },
  { Dia: "Dia 07", Valor: 70, Categoria: "Atual" },
  { Dia: "Dia 07", Valor: 56, Categoria: "Com Novo Produto" },
  { Dia: "Dia 08", Valor: 80, Categoria: "Atual" },
  { Dia: "Dia 08", Valor: 64, Categoria: "Com Novo Produto" },
  { Dia: "Dia 09", Valor: 90, Categoria: "Atual" },
  { Dia: "Dia 09", Valor: 72, Categoria: "Com Novo Produto" },
  { Dia: "Dia 10", Valor: 100, Categoria: "Atual" },
  { Dia: "Dia 10", Valor: 80, Categoria: "Com Novo Produto" },
  { Dia: "Dia 11", Valor: 110, Categoria: "Atual" },
  { Dia: "Dia 11", Valor: 88, Categoria: "Com Novo Produto" },
  { Dia: "Dia 12", Valor: 120, Categoria: "Atual" },
  { Dia: "Dia 12", Valor: 96, Categoria: "Com Novo Produto" },
  { Dia: "Dia 13", Valor: 130, Categoria: "Atual" },
  { Dia: "Dia 13", Valor: 104, Categoria: "Com Novo Produto" },
  { Dia: "Dia 14", Valor: 140, Categoria: "Atual" },
  { Dia: "Dia 14", Valor: 112, Categoria: "Com Novo Produto" },
  { Dia: "Dia 15", Valor: 150, Categoria: "Atual" },
  { Dia: "Dia 15", Valor: 120, Categoria: "Com Novo Produto" },
  { Dia: "Dia 16", Valor: 160, Categoria: "Atual" },
  { Dia: "Dia 16", Valor: 128, Categoria: "Com Novo Produto" },
  { Dia: "Dia 17", Valor: 170, Categoria: "Atual" },
  { Dia: "Dia 17", Valor: 136, Categoria: "Com Novo Produto" },
  { Dia: "Dia 18", Valor: 180, Categoria: "Atual" },
  { Dia: "Dia 18", Valor: 144, Categoria: "Com Novo Produto" },
  { Dia: "Dia 19", Valor: 190, Categoria: "Atual" },
  { Dia: "Dia 19", Valor: 152, Categoria: "Com Novo Produto" },
  { Dia: "Dia 20", Valor: 200, Categoria: "Atual" },
  { Dia: "Dia 20", Valor: 160, Categoria: "Com Novo Produto" },
  { Dia: "Dia 21", Valor: 210, Categoria: "Atual" },
  { Dia: "Dia 21", Valor: 168, Categoria: "Com Novo Produto" },
  { Dia: "Dia 22", Valor: 220, Categoria: "Atual" },
  { Dia: "Dia 22", Valor: 176, Categoria: "Com Novo Produto" },
  { Dia: "Dia 23", Valor: 230, Categoria: "Atual" },
  { Dia: "Dia 23", Valor: 184, Categoria: "Com Novo Produto" },
  { Dia: "Dia 24", Valor: 240, Categoria: "Atual" },
  { Dia: "Dia 24", Valor: 192, Categoria: "Com Novo Produto" },
  { Dia: "Dia 25", Valor: 250, Categoria: "Atual" },
  { Dia: "Dia 25", Valor: 200, Categoria: "Com Novo Produto" },
  { Dia: "Dia 26", Valor: 260, Categoria: "Atual" },
  { Dia: "Dia 26", Valor: 208, Categoria: "Com Novo Produto" },
  { Dia: "Dia 27", Valor: 270, Categoria: "Atual" },
  { Dia: "Dia 27", Valor: 216, Categoria: "Com Novo Produto" },
  { Dia: "Dia 28", Valor: 280, Categoria: "Atual" },
  { Dia: "Dia 28", Valor: 224, Categoria: "Com Novo Produto" },
  { Dia: "Dia 29", Valor: 290, Categoria: "Atual" },
  { Dia: "Dia 29", Valor: 232, Categoria: "Com Novo Produto" },
  { Dia: "Dia 30", Valor: 300, Categoria: "Atual" },
  { Dia: "Dia 30", Valor: 240, Categoria: "Com Novo Produto" },
]
